import tkinter as tk
win = tk.Tk(className='My App')
win.geometry("900x300")
b = tk.Button(win, text = 'Submit')
c = tk.Checkbutton(win, text="Python")
c.pack()
c1 = tk.Checkbutton(win, text="C++")
c1.pack()
c2 = tk.Checkbutton(win, text="Java")
c2.pack()
label1 = tk.Label(win, text="Hi, Welcome to GUI using Tkinter")
label1.pack()
b.pack()
win.mainloop()